ThreeBotPackages/threefold/directory/ActorsFactory.py
ThreeBotPackages/threefold/directory/actors/nodes.py
ThreeBotPackages/threefold/directory/tests/node_tests.py

Signed-off-by: Ashraf Fouda <ashraf.m.fouda@gmail.com>

Fixes nodes actor and add more methods to it

---

ThreeBotPackages/threefold/gridnetwork/actors/gridnetwork.py
ThreeBotPackages/threefold/gridnetwork/examples/cleanup.py
ThreeBotPackages/threefold/gridnetwork/examples/clientsample.py
ThreeBotPackages/threefold/gridnetwork/examples/serverprepation.py
ThreeBotPackages/threefold/gridnetwork/models/tfgrid_network_network_1.toml
ThreeBotPackages/threefold/gridnetwork/start.py

Add gedis network_manager

---

ThreeBotPackages/threefold/tfgrid_workloads/actors/workload_manager.py
ThreeBotPackages/threefold/tfgrid_workloads/models/tfgrid_reservation_container_1.toml
ThreeBotPackages/threefold/tfgrid_workloads/models/tfgrid_reservation_statsaggregator_1.toml
ThreeBotPackages/threefold/tfgrid_workloads/models/tfgrid_reservation_volume_1.toml
ThreeBotPackages/threefold/tfgrid_workloads/models/tfgrid_reservation_zdb_1.toml

Provisioning actors

---

ThreeBotPackages/threebot/calendar/actors/addressbook.py
ThreeBotPackages/threebot/calendar/package.py
ThreeBotPackages/threebot/calendar/radicale/web/fn.js

Signed-off-by: Ashraf Fouda <ashraf.m.fouda@gmail.com>

Adds refactor calendar package

---

ThreeBotPackages/threebot/chat/package.py
ThreeBotPackages/threebot/webinterface/package.py
ThreeBotPackages/threebot/wiki/package.py

start wiki and chat on port 80 as well for easier testing

Initial work for http support

---

ThreeBotPackages/fruum/app.py
ThreeBotPackages/threefold/tfgrid_workloads/WorkloadManagerFactory.py
ThreeBotPackages/threefold/tfgrid_workloads/actors/workload_manager.py
ThreeBotPackages/threefold/tfgrid_workloads/tests/1_base_tests.py

- move the helper classes and function to the factory so we can use them at places other than the actor.
- add handling for delete action in the trigger function. It will also be useful if we add any actors that delete the reservations or something.
- make sure the tests use this index model to clear indices too.
- add test cases for inexistent users.
Fixes https://github.com/threefoldtech/jumpscaleX_threebot/issues/132 
Fixes https://github.com/threefoldtech/jumpscaleX_threebot/issues/90

Handle reservation indices deletion

---

ThreeBotPackages/threebot/chat/static/chat/js/bot_client.js

Add support for forms in chatbot

---

ThreeBotPackages/threefold/tfgrid_workloads/actors/workload_manager.py
ThreeBotPackages/threefold/tfgrid_workloads/tests/1_base_tests.py

see https://github.com/threefoldtech/jumpscaleX_threebot/issues/150

simplify reservation flow for testing

---

ThreeBotPackages/threefold/tfgrid_workloads/actors/workload_manager.py
scripts/delete3bot.py
scripts/setupinfra.py

this is used as a cursor instead of timestamp to avoid
race conditions intdoduced by latency

Use the reservation id for listing

---

ThreeBotPackages/tfgrid/tfgrid_directory/actors/farms.py
ThreeBotPackages/tfgrid/tfgrid_directory/actors/nodes.py
ThreeBotPackages/tfgrid/tfgrid_directory/models/tfgrid_farm_1.toml
ThreeBotPackages/tfgrid/tfgrid_directory/models/tfgrid_node_2.toml

Related to https://github.com/threefoldtech/zos/issues/372 and https://github.com/threefoldtech/zos/pull/373

directory: make farmer id to be an integer

---

ThreeBotPackages/tfgrid/registry/ThreeFoldRegistryFactory.py
ThreeBotPackages/tfgrid/registry/actors/registry.py
ThreeBotPackages/tfgrid/registry/wiki/README.md
ThreeBotPackages/tfgrid/registry/wiki/readme.md

Working on registry client and fix issues related to registry package

Development registry package

---

ThreeBotPackages/zerobot/chat/package.py
ThreeBotPackages/zerobot/chat/templates/chat/home.html
ThreeBotPackages/zerobot/chat/templates/chat/index.html
ThreeBotPackages/zerobot/wiki/package.py
ThreeBotPackages/zerobot/wiki/templates/home.html
ThreeBotPackages/zerobot/wiki/templates/wiki/index.html

* Check all the packages to make sure that they use the global ```weblibs``` not the local one.
* Update the ```wiki``` package to use the global ```weblibs```.
* Update the ```Chat``` package to use the global ```weblibs```.

Development global weblibs

---

ThreeBotPackages/tfgrid/registry/wiki/README.md

update registery package docs

---

ThreeBotPackages/zerobot/wiki/actors/html_test.py
ThreeBotPackages/zerobot/wiki/static/wiki/js/dynamic_content.js
docs/wikis/examples/docs/test_html.md
docs/wikis/macro/dynamic_content.md

Related PR:
https://github.com/threefoldtech/jumpscaleX_libs/pull/36

add docs and examples for markdown support in dynamic_content macro

---

ThreeBotPackages/tfgrid/phonebook/actors/phonebook.py
ThreeBotPackages/tfgrid/registration/actors/registration.py

at the end of the initizliation phase, the 3bot gets a new seed
so we update the public key in the phonebook
part of https://github.com/threefoldtech/jumpscaleX_threebot/issues/118

3bot initalization, update public key in phonebook

---

ThreeBotPackages/zerobot/webinterface/actors/identity.py

added name to identity

---

ThreeBotPackages/tfgrid/tfgrid_directory/actors/farms.py

It was not possible to update a farm without changing the farmname, this is resolved with this change

Fixed update farm requiring to change farmname

---

ThreeBotPackages/zerobot/webinterface/bottle/BottleInterfaceFactory.py

web interface: try to reload gedis client if getting an actor failed

---

ThreeBotPackages/zerobot/chat/templates/chat/login.html

This is how it looks: ![2019-11-14_1507x293_scrot](https://user-images.githubusercontent.com/303164/68865471-296c3b80-06f3-11ea-9a83-b5485b3ab3a2.png)

chat flow: make login icon button and add name of the provider next to it

---

ThreeBotPackages/tfgrid/registry/actors/registry.py
ThreeBotPackages/tfgrid/registry/wiki/README.md

Fixing issues related to Registry #221 #217

Fixing issues related to Registry #221 #217

---

ThreeBotPackages/threebot/contacts/app.py
ThreeBotPackages/threebot/contacts/html/components/contactlistitem/contactlistitem.css
ThreeBotPackages/threebot/contacts/html/components/contactlistitem/contactlistitem.html
ThreeBotPackages/threebot/contacts/html/components/contactlistitem/contactlistitem.js
ThreeBotPackages/threebot/contacts/html/components/contactlistitem/contactlistitem.spec.js
ThreeBotPackages/threebot/contacts/html/components/contactlistitem/index.vue
ThreeBotPackages/threebot/contacts/html/components/fullcontact/fullcontact.css
ThreeBotPackages/threebot/contacts/html/components/fullcontact/fullcontact.html
ThreeBotPackages/threebot/contacts/html/components/fullcontact/fullcontact.js
ThreeBotPackages/threebot/contacts/html/components/fullcontact/fullcontact.spec.js
ThreeBotPackages/threebot/contacts/html/components/fullcontact/index.vue
ThreeBotPackages/threebot/contacts/html/router.json
ThreeBotPackages/threebot/contacts/html/service.js
ThreeBotPackages/threebot/contacts/html/store.js
ThreeBotPackages/threebot/contacts/html/views/contacts/contacts.css
ThreeBotPackages/threebot/contacts/html/views/contacts/contacts.html
ThreeBotPackages/threebot/contacts/html/views/contacts/contacts.js
ThreeBotPackages/threebot/contacts/html/views/contacts/index.vue
ThreeBotPackages/threebot/contacts/meta.toml
ThreeBotPackages/threebot/contacts/package.py

As requested on https://github.com/threefoldtech/home/issues/404 the farmmanagement is moved.

moved contacts back to threebot

---

ThreeBotPackages/tfgrid/tfgrid_workloads/actors/workload_manager.py

fixes #246
Don't merge just yet cause I couldn't test it yet because of : https://github.com/threefoldtech/jumpscaleX_core/issues/236

workload_manager: ensure there is a node_id set for each workload

---

ThreeBotPackages/tfgrid/directory/actors/farm_1_model.py
ThreeBotPackages/tfgrid/directory/actors/location_1_model.py
ThreeBotPackages/tfgrid/directory/actors/node_2_model.py
ThreeBotPackages/tfgrid/registry/actors/registry.py
ThreeBotPackages/zerobot/webplatform/actors/initialize.py
ThreeBotPackages/zerobot/webplatform/package.py

- fix registry
- fix webplatform

Development gedisfixes

---

ThreeBotPackages/tfgrid/registry/actors/registry.py

worked on:
* Load a schema using an actor
* Fixing issue related to loading the data to the model
* Fixing issue related to the returning the desired formatting

Fixing bugs in registry

---

README.md

Add docs for disable crud actor generation for actors.
Issue: https://github.com/threefoldtech/jumpscaleX_core/issues/304

Add disable crud actor generation option in threebot package docs

---

README.md

Edit docs for disable crud actor generation for actors.

Fix typo in threebot readme

---

.3gitconfig.toml
ThreeBotPackages/threefold/simplemail/actors/simplemail.py
ThreeBotPackages/threefold/simplemail/models/models.toml
ThreeBotPackages/threefold/simplemail/package.py
ThreeBotPackages/threefold/simplemail/package.toml
ThreeBotPackages/threefold/simplemail/wiki/README.md

- Add simple mail package and actors

add simple mail package

---

ThreeBotPackages/zerobot/webinterface/package.py

add location for package author info

add location for package author info

---

ThreeBotPackages/tfgrid/directory/actors/nodes.py
ThreeBotPackages/tfgrid/provision_examples/k8s_cluster.py
ThreeBotPackages/tfgrid/workloads/actors/workload_manager.py
ThreeBotPackages/tfgrid/workloads/models/tfgrid_workloads_reservation_result_1.toml
ThreeBotPackages/tfgrid/workloads/models/tfgrid_workloads_reservation_workload_1.toml

Contains some fixing for the directory actors
New support for k8s cluster reservation and example how to create a reservation for it
Also add code to write uptime update of the node into influx for later minting (https://github.com/threefoldtech/zos/issues/357)

Development directory

---

ThreeBotPackages/tfgrid/directory/package.py

- update tfgrid directory location

update tfgrid directory custom location

---

ThreeBotPackages/tfgrid/workloads/actors/workload_manager.py

Fix query in workload_manager

---

ThreeBotPackages/tfgrid/backup_explorer/backup.py
ThreeBotPackages/tfgrid/backup_explorer/restore.py
ThreeBotPackages/tfgrid/threebot_provisioning/chatflows/threebot_deploy.py

https://github.com/threefoldtech/jumpscaleX_core/issues/596
* **code refactor** change property name ```threebot_zdb_sonic_start``` to ```start_servers_threebot_zdb_sonic```

Fixing import and export 

---

ThreeBotPackages/zerobot/webinterface/wiki/wikis/README.md

* Updated the wiki docs
https://github.com/threefoldtech/jumpscaleX_threebot/commit/929b7f537bd6c02b48c5c611580d2fcef18b3d7b

Update wiki docs

---

ThreeBotPackages/demo/fruum/package.toml

Fix demo fruum package bcdb config

---

ThreeBotPackages/tfgrid/dns/actors/namemanager.py
ThreeBotPackages/tfgrid/gateway/actors/gateway.py
ThreeBotPackages/zerobot/packagemanager/actors/package_manager.py

- don't stuck if package or more failed
- timeout blocking actors
- don't install packages just list

fix actors list method in packagemanager

---

ThreeBotPackages/tfgrid_solutions/minio/chatflows/minio_deploy.py

Fix minio to create multiple zdbs based on ratio

---

ThreeBotPackages/tfgrid/workloads/models/tfgrid_workloads_reservation_result_1.toml

Change data_json to type json

---

ThreeBotPackages/tfgrid/gateway/actors/gateway.py

see https://github.com/threefoldtech/jumpscaleX_threebot/issues/470

fix gateway actors

---

ThreeBotPackages/zerobot/codeserver/package.py

Signed-off-by: Ashraf Fouda <ashraf.m.fouda@gmail.com>

Adds install method to codeserver

---

ThreeBotPackages/tfgrid_solutions/tf_simulator/chatflows/tf_simulator_deploy.py
ThreeBotPackages/tfgrid_solutions/tf_simulator/package.py
ThreeBotPackages/tfgrid_solutions/tf_simulator/package.toml

see https://github.com/threefoldtech/home/issues/560

adds tf_simulator chatflow

---

ThreeBotPackages/tfgrid_solutions/any_flist/chatflows/your_flist.py
ThreeBotPackages/tfgrid_solutions/kubernetes_cluster/chatflows/kubernetes_cluster_deploy.py
ThreeBotPackages/tfgrid_solutions/minio/chatflows/minio_deploy.py
ThreeBotPackages/tfgrid_solutions/ubuntu/chatflows/ubuntu_deploy.py

https://github.com/threefoldtech/jumpscaleX_threebot/issues/519

user to specify expiry in solution chatflow

---

ThreeBotPackages/tfgrid/threebot_provisioning/chatflows/threebot_reservation.py
ThreeBotPackages/tfgrid_solutions/any_flist/chatflows/your_flist.py
ThreeBotPackages/tfgrid_solutions/kubernetes_cluster/chatflows/kubernetes_cluster_deploy.py
ThreeBotPackages/tfgrid_solutions/minio/chatflows/minio_deploy.py
ThreeBotPackages/tfgrid_solutions/ubuntu/chatflows/ubuntu_deploy.py

Update chatflows to wait for network deploy

---

ThreeBotPackages/tfgrid/threebot_provisioning/chatflows/threebot_reservation.py
ThreeBotPackages/tfgrid_solutions/any_flist/chatflows/your_flist.py
ThreeBotPackages/tfgrid_solutions/kubernetes_cluster/chatflows/kubernetes_cluster_deploy.py
ThreeBotPackages/tfgrid_solutions/minio/chatflows/minio_deploy.py
ThreeBotPackages/tfgrid_solutions/ubuntu/chatflows/ubuntu_deploy.py

Chatflows: update network after showing confirmation dialog

---

ThreeBotPackages/tfgrid/threebot_provisioning/chatflows/threebot_reservation.py
ThreeBotPackages/tfgrid_solutions/any_flist/chatflows/your_flist.py
ThreeBotPackages/tfgrid_solutions/kubernetes_cluster/chatflows/kubernetes_cluster_deploy.py
ThreeBotPackages/tfgrid_solutions/minio/chatflows/minio_deploy.py
ThreeBotPackages/tfgrid_solutions/ubuntu/chatflows/ubuntu_deploy.py

Update chatflows to wait for reservation

---

ThreeBotPackages/tfgrid/directory/models/tfgrid_directory_farm_1.toml
ThreeBotPackages/tfgrid/workloads/models/tfgrid_workloads_reservation_1.toml
ThreeBotPackages/threebot/farmmanagement/actors/farm_management.py
ThreeBotPackages/threebot/farmmanagement/frontend/components/nodeinfo/index.vue
ThreeBotPackages/threebot/farmmanagement/frontend/components/nodeinfo/nodeinfo.html
ThreeBotPackages/threebot/farmmanagement/frontend/components/nodeinfo/nodeinfo.js
ThreeBotPackages/threebot/farmmanagement/frontend/components/nodestable/index.vue
ThreeBotPackages/threebot/farmmanagement/frontend/components/nodestable/nodestable.html
ThreeBotPackages/threebot/farmmanagement/frontend/components/nodestable/nodestable.js
ThreeBotPackages/threebot/farmmanagement/frontend/services/farmmanagementServices.js
ThreeBotPackages/threebot/farmmanagement/frontend/store/farmmanagement.js
ThreeBotPackages/threebot/farmmanagement/frontend/views/farmmanagement/farmmanagement.html
ThreeBotPackages/threebot/farmmanagement/frontend/views/farmmanagement/farmmanagement.js

goes with https://github.com/threefoldtech/jumpscaleX_libs/pull/145

Unstable reservation payments

---

ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/kubernetes_cluster_deploy.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/minio_deploy.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/ubuntu_deploy.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/your_flist.py

Change kubernetss chatflow to consider cluster_size correct

Check for required units on the nodes

---

ThreeBotPackages/tfgrid/gateway/actors/gateway.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/webgateway_deploy.py

Make it possible to deploy webgateway on custom domain

---

ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/minio_deploy.py

Generate secret for user cause he does not care aslong it's secure

Improve minio flow check for accesskey/secret length

---

ThreeBotPackages/threebot/farmmanagement/frontend/components/nodeinfo/nodeinfo.css
ThreeBotPackages/threebot/farmmanagement/frontend/components/nodeinfo/nodeinfo.html
ThreeBotPackages/threebot/farmmanagement/frontend/components/nodeinfo/nodeinfo.js
ThreeBotPackages/threebot/farmmanagement/frontend/components/nodestable/nodestable.js
ThreeBotPackages/threebot/farmmanagement/frontend/services/farmmanagementServices.js
ThreeBotPackages/threebot/farmmanagement/frontend/store/farmmanagement.js
ThreeBotPackages/threebot/farmmanagement/frontend/views/farmmanagement/farmmanagement.html
ThreeBotPackages/threebot/farmmanagement/frontend/views/farmmanagement/farmmanagement.js

Edit farm settings:
toggle node free to use:

 farm_management: allow to set node free and update farm information 

---

ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/network_deploy.py

expired
reservation_wait already checks expiration prevents busy loops no need
to reinvent that in this flow
See: #583

Chatflows network: Reuse reservation wait to check if reservation

---

ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/kubernetes_cluster_deploy.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/minio_deploy.py

https://github.com/threefoldtech/jumpscaleX_threebot/issues/582

Seperate filters for different kinds of nodes in minio and k8s chatflows

---

ThreeBotPackages/threebot/farmmanagement/frontend/services/farmmanagementServices.js
ThreeBotPackages/threebot/farmmanagement/frontend/store/farmmanagement.js
ThreeBotPackages/threebot/farmmanagement/frontend/views/farmmanagement/farmmanagement.js

see https://github.com/threefoldtech/jumpscaleX_threebot/issues/581

 use the configured explorer in farm management package

---

ThreeBotPackages/tfgrid/threebot_provisioning/chatflows/threebot_reservation.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/kubernetes_cluster_deploy.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/minio_deploy.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/network_deploy.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/ubuntu_deploy.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/your_flist.py

https://github.com/threefoldtech/home/issues/648

Add payment in ubuntu deploy chatflow

---

ThreeBotPackages/threebot/capacity/html/store.js
ThreeBotPackages/threebot/farmmanagement/frontend/components/nodeinfo/nodeinfo.html
ThreeBotPackages/threebot/farmmanagement/frontend/components/nodestable/nodestable.js
ThreeBotPackages/threebot/farmmanagement/frontend/services/farmmanagementServices.js
ThreeBotPackages/threebot/farmmanagement/frontend/store/farmmanagement.js
ThreeBotPackages/threebot/farmmanagement/frontend/views/farmmanagement/farmmanagement.js

only loads the node from a specific farm from server
fixes #607

farm management: fix loading of the nodes

---

ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/domain_delegation.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/kubernetes_cluster_deploy.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/minio_deploy.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/network_deploy.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/solution_expose.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/ubuntu_deploy.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/your_flist.py

Use j.me.tid in all chatflows

---

ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/minio_deploy.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/solution_expose.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/ubuntu_deploy.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/your_flist.py

Make it possible to expose your tls (https) ports

---

ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/domain_delegation.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/network_deploy.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/your_flist.py

https://github.com/threefoldtech/jumpscaleX_threebot/issues/655

validate empty values in chatflows

---

ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/solution_expose.py

https://github.com/threefoldtech/jumpscaleX_threebot/issues/664

Update overview with payment explanation in solution expose chatflow

---

ThreeBotPackages/tfgrid/provision_examples/k8s_cluster.py
ThreeBotPackages/tfgrid/provision_examples/multi_nodes.py
ThreeBotPackages/tfgrid/provision_examples/ubuntu_ssh.py
ThreeBotPackages/tfgrid/provision_examples/ubuntu_ssh_corex.py
ThreeBotPackages/tfgrid/provision_examples/zdb.py
ThreeBotPackages/zerobot/webinterface/actors/identity.py

Fixes threefoldtech/jumpscaleX_threebot#673

Replaced j.myidentities.me (not up-to-date) with j.me

---

ThreeBotPackages/threebot/farmmanagement/frontend/components/nodeinfo/nodeinfo.html
ThreeBotPackages/threebot/farmmanagement/frontend/services/farmmanagementServices.js
ThreeBotPackages/threebot/farmmanagement/frontend/store/farmmanagement.js
ThreeBotPackages/threebot/farmmanagement/frontend/views/farmmanagement/farmmanagement.js

- The getUser used to call getName from the identity actor and then make another call to get the id from the explorer. Now one roundtrip is saved as we get the id and name from the identity actor directly

Farms & Capacity: Getting user Improvement

---

ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/solution_expose.py

Use the currency of the solution as we currently don't mix currencies

Fix gateway expose for currencies that are not freetft

---

ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/solution_expose.py

Restore gw and exposed domains in our solutions pages

---

ThreeBotPackages/threefold/simulator/image/Dockerfile
ThreeBotPackages/threefold/simulator/image/startup.sh

Add Dockferfile to build simulator image

---

ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/network_deploy.py
ThreeBotPackages/zerobot/webinterface/actors/chatbot.py
ThreeBotPackages/zerobot/webinterface/chatflows/App.vue

see https://github.com/threefoldtech/home/issues/715

restore sessions and  their  states in the chatflows

---

ThreeBotPackages/zerobot/admin/actors/package_manager.py

validate package.toml required keys
issue: https://github.com/threefoldtech/jumpscaleX_threebot/issues/593

validate package toml config

---

ThreeBotPackages/threebot/farmmanagement/frontend/components/nodeinfo/nodeinfo.html
ThreeBotPackages/threebot/farmmanagement/frontend/components/nodeinfo/nodeinfo.js
ThreeBotPackages/threebot/farmmanagement/frontend/components/nodestable/nodestable.html
ThreeBotPackages/threebot/farmmanagement/frontend/components/nodestable/nodestable.js
ThreeBotPackages/threebot/farmmanagement/frontend/services/farmmanagementServices.js

Fixes: https://github.com/threefoldtech/tfexplorer/issues/61

Adds reporting of the node's network health

---

ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/domain_delegation.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/solution_expose.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/ubuntu_deploy.py

issue: https://github.com/threefoldtech/jumpscaleX_threebot/issues/723

accept different currencies in free_to_use nodes

---

ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/ubuntu_deploy.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/your_flist.py

See: https://github.com/threefoldtech/jumpscaleX_threebot/issues/722

Make it possible to chooise rootfs size/type

---

ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/solution_expose.py

issue: https://github.com/threefoldtech/home/issues/750
show error message if solution's network no longer exist

better error if network is expired in solution expose

---

ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/ubuntu_deploy.py
ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/your_flist.py

Update phrasing of rootfs questions:

---

ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/minio_deploy.py

- Add support for master/slave setup in minio chatflow
- Change flist used for minio
- Use default entrypoint in flist(by passing empty entrypoint)
https://github.com/threefoldtech/jumpscaleX_threebot/issues/737

Add support in minio chatflow for master/slave setup

---

ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/your_flist.py

Optional attaching of a volume when creating a container using the generic flist chatflow

Add optional volume attach in generic flist deploy chatflow

---

ThreeBotPackages/zerobot/admin/actors/wallet.py

keep loading wallets till only valid ones are remaining

---

ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/models/tfgrid_solutions_network_1.toml

https://github.com/threefoldtech/jumpscaleX_core/issues/892

Add parent network to tfgrid solutions network schema
